In [41]:
l=[1,2,3,4]
l+4  # element wise operations not possible in lists

TypeError: can only concatenate list (not "int") to list

In [2]:
import numpy as np

ar=np.array([1,2,3,4])
ar

array([1, 2, 3, 4])

In [3]:
ar+4

array([5, 6, 7, 8])

In [4]:
## random

a=np.random.randint(1,100,12)  # range, size
a

array([17, 79, 84, 67, 52, 84, 26, 36, 99, 26, 70, 69])

In [5]:
np.random.random()   # 0 to 1

0.6316053933184664

In [6]:
np.random.randint(400)

247

In [7]:

a=np.random.randint(1,100,(2,3))  # range, shape
a

array([[14, 20, 77],
       [47, 59, 68]])

In [14]:

a=np.random.randint(1,100,12)  # range, size
type(a)

numpy.ndarray

In [9]:
a[0]

43

In [10]:
a[1]

39

In [11]:
### slicing

a[::2]

array([43, 92, 62,  9,  1, 29])

In [13]:
a[:5]

array([43, 39, 92, 38, 62])

In [12]:
a[::-1]

array([97, 29, 41,  1, 52,  9, 12, 62, 38, 92, 39, 43])

In [ ]:
### fancy indexing or boolean indexing

In [15]:
a

array([ 4, 11, 48, 86, 17, 64, 56, 45, 30, 13, 39, 66])

In [16]:
a>50

array([False, False, False,  True, False,  True,  True, False, False,
       False, False,  True])

In [17]:
a[a>50]  

array([86, 64, 56, 66])

In [21]:
a[(a>50) & (a<60)]=200

In [22]:
a

array([  4,  11,  48,  86,  17,  64, 200,  45,  30,  13,  39,  66])

In [23]:
def grt(a,b):
    if a>b:
        return a
    else:
        return b
        

In [24]:
grt(90,67)

90

In [26]:
grt([56,43,23],[12,34,25])

[56, 43, 23]

In [27]:
### vectorization is used to implement array operations without using loops

In [28]:
vgrt=np.vectorize(grt)

vgrt([56,43,23],[12,34,25])

array([56, 43, 25])

### stacking:

- vstack  - we can add rows
- hstack  - we can add columns


In [32]:
a1=np.random.randint(1,20,(1,2))
print(a1)
b1=np.random.randint(1,20,(1,2))
print(b1)
print('--vstack--')
np.vstack((a1,b1))

[[19 14]]
[[13  3]]
--vstack--


array([[19, 14],
       [13,  3]])

In [ ]:
### task1:
create an 2D array with 4 elements values b/w 10,20  and apply vstack and hstack on it

In [ ]:
#  task2
create an 1D array with 10 elements and reshape it with 2 rows and 5 columns

In [30]:
a1

array([[12, 11]])

In [33]:
a1=np.random.randint(1,20,(1,2))
print(a1)
b1=np.random.randint(1,20,(1,2))
print(b1)
print('--hstack--')
np.hstack((a1,b1))

[[6 4]]
[[4 7]]
--hstack--


array([[6, 4, 4, 7]])

In [34]:
### ravel() and flatten()

In [39]:
a1=np.array([[4,5],[7,8]])
print(a1.ndim)
a1

2


array([[4, 5],
       [7, 8]])

In [38]:
b1=a1.flatten()
b1

array([4, 5, 7, 8])

In [40]:
c1=a1.ravel()
c1

array([4, 5, 7, 8])